### ISSUE TITLE
Test failed: requirements.txt

### ISSUE THREAD

**Issue by Saurabh-97** [Zhuolin0212/Connect-Your-Neurons#5]
Keras version not found. We need to change it

**Comment by Shahil98** [comment]
We are using the newer version of tensorflow and so we do not require an extra keras library. I will remove the keras library in requirements file and add the appropriate tensorflow version.

**Comment by Saurabh-97** [comment]
We need to remove the excess libraries now: pandas, scikit learn

**Comment by Shahil98** [comment]
Yes, I am removing scikit-learn, pandas, wheel, pip and keras.

**Comment by Shahil98** [comment]
I have updated the requirements.txt file to add an appropriate TensorFlow version and removed excess libraries.
