### ISSUE TITLE
Flake8 test failed

### ISSUE THREAD

**Issue by Saurabh-97** [Zhuolin0212/Connect-Your-Neurons#8]
Check: [travis-build](https://travis-ci.org/github/Zhuolin0212/Connect-Your-Neurons/builds/728785394)
Need to format the concerned files

**Comment by Shahil98** [comment]
We should reduce the line sizes at many places in test_class.py to make it under 79 characters per line to resolve this issue.

**Comment by Saurabh-97** [comment]
Check other files too

**Comment by Saurabh-97** [comment]
The tests passed
